// Hak Cipta (c) 2021 Adam Notodikromo.
// Hak cipta dilindungi undang-undang.
// Penggunaan tunduk pada aturan lisensi.

sidang(Nirdefinisi, fn () {
    ada identitas = fn (x) { x }

    ia("itu Nirdefinisi", fn () {
        tuntut Nirdefinisi itu Kelas
        tuntut Nirdefinisi itu Objek

        tuntut nil itu Nirdefinisi
        tuntut nil itu Objek
    })

    tentang(".kosong?()", fn () {
        ia("mengutus `benar`", fn () {
            tuntut nil.kosong? == benar
        })
    })
})
