sidang("Kata kunci `itu`", fn () {
    ia("bernilai benar jika suatu objek adalah instansi kelas yang benar", fn () {
        tuntut [] itu Deret
        tuntut [] itu Objek
    })

    ia("tuntutan hanya bisa dilakukan dengan kelas", fn () {
       ada a = "BukanKelas"

       coba {
           tuntut "" itu a
           salah
       } tahan (e) {
           tuntut e.pesan() == "seharusnya bertipe Kelas, tapi menerima Kata"
           tuntut e itu MasalahEksekusi
       }
    })
})
